### ISSUE TITLE
it seems that the test file of cec2022 is not existed？

### ISSUE THREAD

**Issue by pjw2146087** [ewarchul/cec#3]

**Comment by yangyongkang2000** [comment]
I recommend an open-source C++ benchmarking framework for single-objective evolutionary optimization algorithms. You can find it at https://github.com/yangyongkang2000/SEvoBench.

**Comment by ewarchul** [comment]
Hi @pjw2146087, I worked on `cec` at the beginning of my PhD, and after making this code usable enough for my purposes, it became an abandonware. For this reason, this project is far from being well-developed and don't expect too much from that :-)

Recently, in my spare time, I've started to rewrite `cec` in C++20 to address performance issues, simplify API, and deliver missed things like proper tests or bindings to Python or R.  Due to limited spare time, I am not sure when it will be ready to replace current trunk. 

Cheers.
